### ISSUE TITLE
debian error

### ISSUE THREAD

**Issue by matuph** [Niam5/Eluna-CMaNGOS-TBC#1]
hello there is an error in the compiling process.
the error occurs with debian 11 updates

/home/matuph/source/cmangos/Eluna-CMaNGOS-TBC/src/game/Chat/ChatHandler.cpp: In member function ‘void WorldSession::HandleTextEmoteOpcode(WorldPacket&)’:
/home/matuph/source/cmangos/Eluna-CMaNGOS-TBC/src/game/Chat/ChatHandler.cpp:734:38: error: ‘text_emote’ was not declared in this scope; did you mean ‘textEmote’?
  734 |     sEluna->OnTextEmote(GetPlayer(), text_emote, emoteNum, guid);
      |                                      ^~~~~~~~~~
      |                                      textEmote

fix :
Eluna-CMaNGOS-TBC/src/game/Chat/ChatHandler.cpp  732-735

#ifdef BUILD_ELUNA
    // used by eluna
    sEluna->OnTextEmote(GetPlayer(), textEmote, emoteNum, guid);
#endif

thank you for the project

**Comment by Niam5** [comment]
Sorry this took a bit to see. I didn't get notified by email from GitHub. I don't know why this slipped past the CI build but it has been resolved in the latest commits to both repositories. Please try to build again.
