### ISSUE TITLE
DBGuid: 9013568) May I ask what the error message is

### ISSUE THREAD

**Issue by wanglinb741** [Niam5/Eluna-CMaNGOS-TBC#10]
DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1713001, command 26 source can not attack (Attacker: Creature (Entry: 18180 Counter: 64963) DBGuid: 64963, Target: Creature (Entry: 17130 Counter: 9013568) DBGuid: 9013568)
 DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1713001, command 26 source can not attack (Attacker: Creature (Entry: 18200 Counter: 64976) DBGuid: 64976, Target: Creature (Entry: 17130 Counter: 9013568) DBGuid: 9013568)

**Comment by wanglinb741** [comment]
The other thing is that the simulator will crash after running for a while

**Comment by wanglinb741** [comment]
Critical Error: A condition which must never be false was found to be false. Server was shut down to protect data integrity.
If this error is occurring frequently, please recompile the software in debug mode to get more details.

WorldObject::GetMap(): m_currMap

**Comment by Niam5** [comment]
Likely an error introduced in a database update somewhere. Not related to the core files nor eluna.
