### ISSUE TITLE
The other thing is that the simulator will crash after running for a while  

### ISSUE THREAD

**Issue by wanglinb741** [Niam5/Eluna-CMaNGOS-TBC#11]
Critical Error: A condition which must never be false was found to be false. Server was shut down to protect data integrity.
If this error is occurring frequently, please recompile the software in debug mode to get more details.

WorldObject::GetMap(): m_currMap

**Comment by Niam5** [comment]
need to provide more info. are you using any additional options turned on, ie bots, solocraft, scripts you are running, etc
