### ISSUE TITLE
All pets don't enter into combat with player

### ISSUE THREAD

**Issue by Arnibou** [Niam5/Eluna-CMaNGOS-TBC#13]
With Lua_engine on:

All pets don't enter into combat with player when player aggro the pet (in ranged for example):
Owner don't enter into combat either and the pet evade directly.

Contrariwise, if player attack owner, the pet enter into combat normaly.

For example:

.go crea 36965

Attack in ranged Moonstalker Runt (Moonstalker Matriarch's pet) to see the bug.

or other example:

.go crea 33238

Attack imp or voidwalker in ranged (Bleakheart Hellcaller's pet)

Without lua engine: it's work fine !

**Comment by Arnibou** [comment]
In Unit.cpp
The problem is here:
![Capture d'écran 2024-05-23 183336](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/assets/8267472/9057283e-a4da-443e-8176-a97752c751a5)
If you comment on this part, it works !

**Comment by Niam5** [comment]
That code block was put there due to another crash that happened with a script written by someone that made an npc a pet and it going into combat wouldn't put the owner in combat and crash so it really cant be removed. Ill have to see if I can get it more limited.

**Comment by Niam5** [comment]
Change the "else if (elunaEvents)" at line 8537 to "else if (elunaEvents && controller->IsPlayer())". That seems to fix the behavior and shouldn't break the script.

**Comment by Arnibou** [comment]
ah ok, I was wondering what it was for, it works like this !
