### ISSUE TITLE
Log in to play the game for a while after quitting the game can not enter the login game

### ISSUE THREAD

**Issue by wanglinb741** [Niam5/Eluna-CMaNGOS-TBC#6]
SQL: SELECT expires_at FROM ip_banned WHERE (expires_at = banned_at OR expires_at > UNIX_TIMESTAMP()) AND ip = '192.168.235.1'
query ERROR: MySQL server has gone away
SQL: SELECT id,locked,lockedIp,gmlevel,v,s,token FROM account WHERE username = 'Z789'
query ERROR: MySQL server has gone away
SQL: SELECT expires_at FROM ip_banned WHERE (expires_at = banned_at OR expires_at > UNIX_TIMESTAMP()) AND ip = '192.168.235.1'
query ERROR: MySQL server has gone away
SQL: SELECT id,locked,lockedIp,gmlevel,v,s,token FROM account WHERE username = 'Z789'
query ERROR: MySQL server has gone away

**Comment by Niam5** [comment]
not a core issue. your mysql server is timing out.
