### ISSUE TITLE
core crash by ElunaEventProcessor()

### ISSUE THREAD

**Issue by betayi** [Niam5/Eluna-CMaNGOS-TBC#7]
coredump info:
![image](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/assets/37472600/1d6e3fa7-ab29-4a9f-bde4-eaa20e393b44)

Program terminated with signal SIGSEGV, Segmentation fault.  
#0  0x000055a2dc27d9bc in ElunaEventProcessor::~ElunaEventProcessor() ()

and always trigger 3-4 times a event at a time , not sure what happed 

comitte:
![image](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/assets/37472600/532e538a-8bf5-47a3-9c11-fa132f93550c)

**Comment by betayi** [comment]
and it seemd the eluna engine was restart itself very frequently

**Comment by Niam5** [comment]
change compat mode in config to "false" and see if any change. Theres a known issue with crashes and compat mode set to "true".

**Comment by betayi** [comment]
> change compat mode in config to "false" and see if any change. Theres a known issue with crashes and compat mode set to "true".

false is the default option,and crash repeat still

**Comment by betayi** [comment]
![image](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/assets/37472600/1c9f981f-04c7-4925-a58e-922ba5622fd7)
![image](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/assets/37472600/3e3e8ab9-6621-4ee7-90d7-fe17f8aeaa7b)

**Comment by betayi** [comment]
turn the switch to "true" , the crash vanished    -_-!

but it still be a problem , core should not crash by a bool choice argument

**Comment by Niam5** [comment]
Unable to reproduce. Unless you provide ALL scripts running and conditions that trigger the crash I am unable to assist.
