### ISSUE TITLE
leaves Arena-2v2 and the server card stops running

### ISSUE THREAD

**Issue by wanglinb741** [Niam5/Eluna-CMaNGOS-TBC#8]
Table `game_graveyard_zone` incomplete: Map 530 Zone 3479 Area 3479 Team 469 does not have a linked graveyard.
Table `game_graveyard_zone` incomplete: Map 530 Zone 3479 Area 3479 Team 469 does not have a linked graveyard.
Table `game_graveyard_zone` incomplete: Map 530 Zone 3479 Area 3479 Team 469 does not have a linked graveyard.
Table `game_graveyard_zone` incomplete: Map 530 Zone 3479 Area 3479 Team 469 does not have a linked graveyard.
Bot #343 A:19 <Dotda> leaves Arena - 2v2
Bot #3602 H:11 <Voowe> leaves Arena - 2v2
Table `game_graveyard_zone` incomplete: Map 530 Zone 3479 Area 3479 Team 469 does not have a linked graveyard.
Bot #437 A:10 <Divo> leaves Arena - 2v2
What can you do to solve this problem? Thank you

**Comment by Niam5** [comment]
Looks to be an issue with the bots. Unless you can provide a crash log indicating its eluna related you will need to see if the bots project maintainer can assist.
